### PR TITLE
Improve Performance & Battery Life: Disable Boost, Fix Audio, & Set Timer Freq

### PR DESCRIPTION
**Pull request by taalojarvi**
Hi @David112x,

RFC on this pull request that implements the following changes: 

- Disables CPU Input Boost and Devfreq boost: These features consume significant power for minimal performance gains. Recommend switching to SCHED_WALT for better UX instead.
- Reverts audio playback while charging fix: The previous patch removed a feature to fix logspam. This change reverts the unnecessary removal and focuses on fixing the logspam issue itself. 
- Reverts force fast charging: Force fast charging is not recommended and can potentially be dangerous. This change reverts the commits related to it.
- Sets timer frequency to 300 Hz: Aligns with Google's recommendations for jitter reduction.

These changes aim to improve overall device performance and battery life without sacrificing essential features.

Additional Notes:

- For more details on the timer frequency change, please refer to the provided link: https://source.android.com/docs/core/tests/debug/jank_jitter#long_threads

### CODE REVIEW

**Comment by David112x** [comment]
I'm a bit skeptical about some of the changes that we're done here, while disabling CPU Input Boosting is fine, I'm not so sure about disabling devfreq boosting, it would require testing with PixelOS (check to see if the PowerHAL is able to access the devices it uses), as for bringing back the ability to use headphones over USB, this feature is nearly useless, so it doesn't make sense to keep a feature that can be deprecated (most people use either headphones on the jack or bluetooth headphones)

Removing FFC seems like an okay change, though it had it's usability (for me, but this is due to the bad charging port that I have)

Switching to Full LTO doesn't seem that good of a change to me, considering how GitHub Actions doesn't have that many resources for builds to not take _too long_ with Full LTO, which was the whole reason why Thin LTO was used to begin with.

The only changes that are conflicting to me are:
- [Revert "techpack/audio: Fix Ximi bug"](https://github.com/sunscape-stuff/kernel_xiaomi_surya/pull/1/commits/8cc3ed014225b52c83c2bedf1cf8ef38a8122a89)
- [drivers: power: Fix audio while charging](https://github.com/sunscape-stuff/kernel_xiaomi_surya/pull/1/commits/c045bc81eada6c9849019abb7a532c5a39b650fa)

Disabling devfreq boosting requires testing to see if the userspace-related things still works as it all should, but no CIB is fine.

**Comment by taalojarvi** [comment]
[GitHub actions now run on a 4C8T Ryzen threadripper.](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners). It should be capable of running Full LTO in a pretty decent time frame. Let's not lose a few extra benchmarkpoints™ on a longer build time. 


[Here's a build of WSL2's linux kernel which was built in 16 minutes](https://github.com/taalojarvi/Stratosphere-Kernel-WSL2/actions/runs/9824953867) 

To further reduce compile times, I can hookup ccache to your pipeline. That should bring down the duration by a significant margin

**Comment by taalojarvi** [comment]
Made the  changes that you've requested. Added some memory management tweaks as well

**Comment by David112x** [comment]
> [GitHub actions now run on a 4C8T Ryzen threadripper.](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners). It should be capable of running Full LTO in a pretty decent time frame. Let's not lose a few extra benchmarkpoints™ on a longer build time.
> 
> [Here's a build of WSL2's linux kernel which was built in 16 minutes](https://github.com/taalojarvi/Stratosphere-Kernel-WSL2/actions/runs/9824953867)
> 
> To further reduce compile times, I can hookup ccache to your pipeline. That should bring down the duration by a significant margin

While GitHub Actions may be able to run builds on it's own with Full LTO, this is going to affect builds on my machine (building kernel with Android) and I haven't been able to get a VPS from DigitalOcean that's capable of building Android without any issues (one of the main issues being time).

**Comment by taalojarvi** [comment]
> > [GitHub actions now run on a 4C8T Ryzen threadripper.](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners). It should be capable of running Full LTO in a pretty decent time frame. Let's not lose a few extra benchmarkpoints™ on a longer build time.
> > [Here's a build of WSL2's linux kernel which was built in 16 minutes](https://github.com/taalojarvi/Stratosphere-Kernel-WSL2/actions/runs/9824953867)
> > To further reduce compile times, I can hookup ccache to your pipeline. That should bring down the duration by a significant margin
> 
> While GitHub Actions may be able to run builds on it's own with Full LTO, this is going to affect builds on my machine (building kernel with Android) and I haven't been able to get a VPS from DigitalOcean that's capable of building Android without any issues (one of the main issues being time).

Added conditional logic to subvert this issue. Not the ideal way to deal with this but it'll have to do for now

**Pull request closed without merging**
